name: Build and Push to ECR

on:
  push:
    branches:
      - '**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get branch and commit info
        id: vars
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Load variables into shell
        run: |
          source $GITHUB_ENV
          echo "BRANCH=$BRANCH"
          echo "SHA=$SHA"

      - name: Build image
        run: |
          source $GITHUB_ENV
          IMAGE_URI=930354804502.dkr.ecr.us-east-1.amazonaws.com/showip
          docker build -t $IMAGE_URI:latest .
          docker tag $IMAGE_URI:latest $IMAGE_URI:showip-${BRANCH}-${SHA}

      - name: Push image to ECR
        run: |
          source $GITHUB_ENV
          IMAGE_URI=930354804502.dkr.ecr.us-east-1.amazonaws.com/showip
          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:showip-${BRANCH}-${SHA}
